config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: ['www', 'scheduler']}
  get 'bonuses/new'

  get 'calendar_event/new'

  get 'contact_form/new'

  get 'contact_form/create'

  get 'tags/index'

  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      resources :appointments
      resources :corporations
    end
  end

  devise_for :users, controllers: {
    invitations: "invitations",
    sessions: "sessions",
    registrations: "registrations"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :users, only: [:index, :edit, :update]


  resources :plannings do
  	resources :appointments, except: [:destroy, :new]
  	resources :recurring_appointments, except: :destroy
    resources :private_events, except: :new
    resources :wished_slots
    resources :nurses
    resources :patients
    resources :activities
    resources :printing_options, only: :show
    resources :teams, only: :show
  end

  resources :services

  resources :care_manager_corporations do
    resources :care_managers
  end

  resources :calendar_events, only: :new

  resources :salary_line_items, only: [:update, :destroy]

  resources :patients do 
    resources :care_plans
  end

  resources :posts

  resources :appointments, except: [:destroy, :new] do
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :recurring_appointments do 
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :completion_reports, only:[:index, :destroy]

  resources :nurses do
    resources :salary_line_items, except: [:new]
    resources :bonuses, only: :new
    resources :nurse_service_wages, only: :index
    resources :completion_reports, only: :index
  end

  resources :corporations do
    resources :nurses, only: :index
    resources :patients, only: :index
    resources :printing_options, only: :update
  end

  resources :dashboard, only: :index

  resources :teams

  resources :contact_forms, only: [:new, :create]

  resources :salary_rules


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #custom routes for static pages
  get "/pages/*page" => "pages#show", as: :pages

  #custom routes for teams
  get 'plannings/:planning_id/teams/:id/payable' => 'teams#payable', as: :planning_team_payable
  get 'plannings/:planning_id/teams/:id/master' => 'teams#master', as: :planning_team_master
  get 'teams/:id/revenue_per_nurse_report' => 'teams#revenue_per_nurse_report', as: :team_revenue_per_nurse_report
  get 'teams/:id/new_master_to_schedule' => 'teams#new_master_to_schedule', as: :new_team_master_to_schedule
  patch 'teams/:id/master_to_schedule' => 'teams#master_to_schedule', as: :team_master_to_schedule
  get 'teams/:id/completion_reports_summary' => 'teams#completion_reports_summary', as: :team_completion_reports_summary


  #custom routes for corporations
  get 'corporations/:id/revenue_per_team_report' => 'corporations#revenue_per_team_report', as: :corporation_revenue_per_team_report
  get 'corporations/:id/new_email_monthly_nurse_wages' => 'corporations#new_email_monthly_nurse_wages', as: :corporation_new_email_monthly_nurse_wages
  get 'corporations/:id/email_monthly_nurse_wages' => 'corporations#email_monthly_nurse_wages', as: :corporation_email_monthly_nurse_wages

  #custom routes for users
  patch 'users/:id/toggle_admin' => 'users#toggle_admin', as: :toggle_admin
  get 'users/:id/edit_role' => 'users#edit_role', as: :edit_user_role
  patch 'users/:id/update_role' => 'users#update_role', as: :update_user_role
  get 'users/current_user_home' => 'users#current_user_home', as: :current_user_home
  
  #custom routes for nurses
  get 'plannings/:planning_id/nurses/:id/payable' => 'nurses#payable', as: :planning_nurse_payable
  get 'nurses/:id/new_reminder_email' => 'nurses#new_reminder_email', as: :nurse_new_reminder_email
  patch 'nurses/:id/send_reminder_email' => 'nurses#send_reminder_email', as: :nurse_send_reminder_email
  patch 'nurses/:id/master_to_schedule' => 'nurses#master_to_schedule', as: :nurse_master_to_schedule
  get 'nurses/:id/new_master_to_schedule' => "nurses#new_master_to_schedule", as: :new_nurse_master_to_schedule
  get 'master_availabilities/nurses' => 'nurses#master_availabilities', as: :nurses_master_availabilities
  patch 'nurses/:id/archive' => 'nurses#archive', as: :nurse_archive
  patch 'nurses/:id/recalculate_salary' => 'nurses#recalculate_salary', as: :nurse_recalculate_salary
  get 'smart_search/nurses' => 'nurses#smart_search', as: :nurses_smart_search
  get 'smart_search_results/nurses' => 'nurses#smart_search_results', as: :nurses_smart_search_results

  #custom routes for patients
  patch 'patients/:id/toggle_active' => 'patients#toggle_active', as: :toggle_active
  patch 'patients/:id/master_to_schedule' => 'patients#master_to_schedule', as: :patient_master_to_schedule
  get 'patients/:id/new_master_to_schedule' => "patients#new_master_to_schedule", as: :new_patient_master_to_schedule
  get 'plannings/:planning_id/patients/:id/payable' => 'patients#payable', as: :planning_patient_payable
  get 'patients/:id/commented_appointments' => 'patients#commented_appointments', as: :patient_commented_appointments
  get 'patients/:id/teikyohyo' => 'patients#teikyohyo', as: :patient_teikyohyo
  get 'patients/:id/new_extract_care_plan' => 'patients#new_extract_care_plan', as: :patient_new_extract_care_plan
  get 'patients/:id/extract_care_plan' => 'patients#extract_care_plan', as: :patient_extract_care_plan
  get 'search_by_kana_group/patients' => 'patients#search_by_kana_group', as: :patients_search_by_kana_group
  get 'patients/:id/completion_reports_summary' => 'patients#completion_reports_summary', as: :patient_completion_reports_summary

  #custom routes for plannings
  get 'plannings/:id/monthly_general_report' => 'plannings#monthly_general_report', as: :planning_monthly_general_report
  get 'plannings/:id/monthly_appointments_report' => 'plannings#monthly_appointments_report', as: :planning_monthly_appointments_report
  get 'plannings/:id/teams_report' => 'plannings#teams_report', as: :planning_teams_report
  get 'plannings/:id/recent_patients_report' => 'plannings#recent_patients_report', as: :planning_recent_patients_report
  get 'plannings/:id/master' => 'plannings#master', as: :planning_master
  get 'plannings/:id/all_nurses_payable' => 'plannings#all_nurses_payable', as: :planning_all_nurses_payable
  get 'plannings/:id/all_patients_payable' => 'plannings#all_patients_payable', as: :planning_all_patients_payable
  get 'plannings/:id/duplicate_from' => 'plannings#duplicate_from', as: :planning_duplicate_from
  patch 'plannings/:id/duplicate' => 'plannings#duplicate', as: :planning_duplicate
  patch 'plannings/:id/master_to_schedule' => 'plannings#master_to_schedule', as: :master_to_schedule
  get 'plannings/:id/new_master_to_schedule' => 'plannings#new_master_to_schedule', as: :new_planning_master_to_schedule
  get 'plannings/:id/cancelled_report' => 'plannings#cancelled_report', as: :planning_cancelled_report  
  get 'plannings/:id/completion_reports_summary' => 'plannings#completion_reports_summary', as: :planning_completion_reports_summary

  #custom routes for appointments
  patch 'plannings/:planning_id/appointments/:id/toggle_cancelled' => 'appointments#toggle_cancelled', as: :planning_appointment_toggle_cancelled
  patch 'plannings/:planning_id/appointments/:id/toggle_edit_requested' => 'appointments#toggle_edit_requested', as: :planning_appointment_toggle_edit_requested
  patch 'plannings/:planning_id/appointments/:id/archive' => 'appointments#archive', as: :planning_appointment_archive
  get 'new_batch_action/appointments' => 'appointments#new_batch_action', as: :new_appointments_batch_action
  get 'batch_action_confirm/appointments' => 'appointments#batch_action_confirm', as: :appointments_batch_action_confirm
  patch 'batch_archive/appointments' => 'appointments#batch_archive', as: :appointments_batch_archive
  patch 'batch_cancel/appointments' => 'appointments#batch_cancel', as: :appointments_batch_cancel
  patch 'batch_restore_to_operational/appointments' => 'appointments#batch_restore_to_operational', as: :appointments_batch_restore_to_operational
  patch 'batch_request_edit/appointments' => 'appointments#batch_request_edit', as: :appointments_batch_request_edit 
  patch 'appointments/:id/toggle_verified' => 'appointments#toggle_verified', as: :toggle_verified_appointment
  patch 'appointments/:id/toggle_second_verified' => 'appointments#toggle_second_verified', as: :toggle_second_verified_appointment
  get 'appointments/:id/new_cancellation_fee' => 'appointments#new_cancellation_fee', as: :appointment_new_cancellation_fee
  get 'appointments_by_category_report/appointments' => 'appointments#appointments_by_category_report', as: :appointments_by_category_report
  get 'monthly_revenue_report/appointments' => 'appointments#monthly_revenue_report', as: :appointments_monthly_revenue_report

  #custom routes for recurring_appointments
  patch 'planning/:planning_id/recurring_appointments/:id/archive' => 'recurring_appointments#archive', as: :planning_recurring_appointment_archive
  patch 'plannings/:planning_id/recurring_appointments/:id/terminate' => 'recurring_appointments#terminate', as: :planning_recurring_appointment_terminate 
  patch 'plannings/:planning_id/recurring_appointments/:id/create_individual_appointments' => 'recurring_appointments#create_individual_appointments', as: :planning_recurring_appointment_create_individual_appointments

  #custom routes for nurse_service_wages
  patch 'nurses/:nurse_id/services/:service_id/set_nurse_wage' => 'nurse_service_wages#set_nurse_wage', as: :set_nurse_service_wage

  #custom routes for tags
  get '/tags' => 'tags#index'

  #custom routes for dashboard

app/models/printing_option.rb
class PrintingOption < ApplicationRecord
end

app/controllers/printing_options_controller.rb
class PrintingOptionsController < ApplicationController

    def show
        authorize current_user, :has_admin_access?
        
        @corporation = current_user.corporation
        @planning = Planning.find(params[:planning_id])
        @printing_option = PrintingOption.find(params[:id])
        @main_nurse = current_user.nurse ||= @corporation.nurses.displayable.order_by_kana.first
    end
    
    def update
        authorize current_user, :has_admin_access?
        
        @printing_option = PrintingOption.find(params[:id])

        if @printing_option.update(printing_option_params)
            redirect_back(fallback_location: current_user_home_path, notice: '印刷設定が登録されました。')
        end
    end

    private

    def printing_option_params
        params.require(:printing_option).permit(:print_patient_comments, :print_nurse_comments, :print_patient_comments_in_master, :print_nurse_comments_in_master, :print_patient_dates, :print_nurse_dates, :print_patient_dates_in_master, :print_nurse_dates_in_master, :print_patient_description, :print_nurse_description, :print_patient_description_in_master, :print_nurse_description_in_master, :print_saturday_availabilities, :print_sunday_availabilities)
    end



end

app/views/printing_options/show.html.erb
<% if request.variant.phone? %>
    <%= render partial: 'plannings/phone_bottom_menu', locals: {view: 'settings', resource_payable_path: planning_nurse_payable_path(@planning, @main_nurse, params: {m: Date.today.in_time_zone('Tokyo').month, y: Date.today.in_time_zone('Tokyo').year})} %>
<% else %>
    <%= render partial: 'plannings/planning_left_menu', locals: {view: 'settings', resource_payable_path: planning_nurse_payable_path(@planning, @main_nurse, params: {m: Date.today.in_time_zone('Tokyo').month, y: Date.today.in_time_zone('Tokyo').year})} %>
<% end %>

<%= render 'plannings/settings_submenu', view: "printing_options" %>

<div id="menu-backdrop">
</div>

<div id="settings-container">
    <div id="printing-options" >
        <div id="planning-header">
            <div id="detail-planning-title">
                <div id="settings-menu">
                    <div id="payable-menu">
                    <%= image_tag 'hamburger_icon_white.svg', size: '35', class: 'hamburger_menu'  %>
                    </div>
                    <p class="planning-activity-module-title setting-title">
                        印刷オプション
                    </p>
                </div>
            </div>
        </div>

        <div class="settings-body">
            <%= form_for [@corporation, @printing_option] do |form| %>

                <div class='colibri-form-subsection'>
                    <div class='colibri-form-subsection-title '>コメント</div>
                    <div class="form-group row">
                        <%= form.label :print_nurse_comments, "個別従業員のコメント", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_nurse_comments,  class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_patient_comments, "個別利用者のコメント", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_patient_comments, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_nurse_comments_in_master, "マスター従業員のコメント", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_nurse_comments_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_patient_comments_in_master, "マスター利用者のコメント", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_patient_comments_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>
                </div>

                <div class='colibri-form-subsection'>
                    <div class='colibri-form-subsection-title'>備考</div>
                    <div class="form-group row">
                        <%= form.label :print_nurse_description, "個別従業員の備考", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_nurse_description, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_patient_description, "個別利用者の備考", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_patient_description, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_nurse_description_in_master, "マスター従業員の備考", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_nurse_description_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_patient_description_in_master, "マスター利用者の備考", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_patient_description_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                </div>

                <div class='colibri-form-subsection'>
                    <div class='colibri-form-subsection-title'>日付</div>
                    <div class="form-group row">
                        <%= form.label :print_nurse_dates_in_master, "マスター従業員の日付", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_nurse_dates_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_patient_dates_in_master, "マスター利用者の日付", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_patient_dates_in_master, class: "col-sm-3 print-option-checkbox" %>
                    </div>         
                </div>

                <div class='colibri-form-subsection'>
                    <div class='colibri-form-subsection-title'>空き情報</div>
                    <div class="form-group row">
                        <%= form.label :print_saturday_availabilities, "土曜日の空き情報", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_saturday_availabilities, class: "col-sm-3 print-option-checkbox" %>
                    </div>

                    <div class="form-group row">
                        <%= form.label :print_sunday_availabilities, "日曜日の空き情報", class: "colibri-form-label-dark col-sm-9" %>
                        <%= form.check_box :print_sunday_availabilities, class: "col-sm-3 print-option-checkbox" %>
                    </div>         
                </div>

                <div class="actions">
                    <%= form.submit "セーブする", class: "btn btn-info btn-block" %>
                </div>
            <% end %>
        </div>
    </div>

</div>