config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: ['www', 'scheduler']}
  get 'bonuses/new'

  get 'calendar_event/new'

  get 'contact_form/new'

  get 'contact_form/create'

  get 'tags/index'

  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      resources :appointments
      resources :corporations
    end
  end

  devise_for :users, controllers: {
    invitations: "invitations",
    sessions: "sessions",
    registrations: "registrations"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :users, only: [:index, :edit, :update]


  resources :plannings do
  	resources :appointments, except: [:destroy, :new]
  	resources :recurring_appointments, except: :destroy
    resources :private_events, except: :new
    resources :wished_slots
    resources :nurses
    resources :patients
    resources :activities
    resources :printing_options, only: :show
    resources :teams, only: :show
  end

  resources :services

  resources :care_manager_corporations do
    resources :care_managers
  end

  resources :calendar_events, only: :new

  resources :salary_line_items, only: [:update, :destroy]

  resources :patients do 
    resources :care_plans
  end

  resources :posts

  resources :appointments, except: [:destroy, :new] do
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :recurring_appointments do 
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :completion_reports, only:[:index, :destroy]

  resources :nurses do
    resources :salary_line_items, except: [:new]
    resources :bonuses, only: :new
    resources :nurse_service_wages, only: :index
    resources :completion_reports, only: :index
  end

  resources :corporations do
    resources :nurses, only: :index
    resources :patients, only: :index
    resources :printing_options, only: :update
  end

  resources :dashboard, only: :index

  resources :teams

  resources :contact_forms, only: [:new, :create]

  resources :salary_rules


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #custom routes for static pages
  get "/pages/*page" => "pages#show", as: :pages

  #custom routes for teams
  get 'plannings/:planning_id/teams/:id/payable' => 'teams#payable', as: :planning_team_payable
  get 'plannings/:planning_id/teams/:id/master' => 'teams#master', as: :planning_team_master
  get 'teams/:id/revenue_per_nurse_report' => 'teams#revenue_per_nurse_report', as: :team_revenue_per_nurse_report
  get 'teams/:id/new_master_to_schedule' => 'teams#new_master_to_schedule', as: :new_team_master_to_schedule
  patch 'teams/:id/master_to_schedule' => 'teams#master_to_schedule', as: :team_master_to_schedule
  get 'teams/:id/completion_reports_summary' => 'teams#completion_reports_summary', as: :team_completion_reports_summary


  #custom routes for corporations
  get 'corporations/:id/revenue_per_team_report' => 'corporations#revenue_per_team_report', as: :corporation_revenue_per_team_report
  get 'corporations/:id/new_email_monthly_nurse_wages' => 'corporations#new_email_monthly_nurse_wages', as: :corporation_new_email_monthly_nurse_wages
  get 'corporations/:id/email_monthly_nurse_wages' => 'corporations#email_monthly_nurse_wages', as: :corporation_email_monthly_nurse_wages

  #custom routes for users
  patch 'users/:id/toggle_admin' => 'users#toggle_admin', as: :toggle_admin
  get 'users/:id/edit_role' => 'users#edit_role', as: :edit_user_role
  patch 'users/:id/update_role' => 'users#update_role', as: :update_user_role
  get 'users/current_user_home' => 'users#current_user_home', as: :current_user_home
  
  #custom routes for nurses
  get 'plannings/:planning_id/nurses/:id/payable' => 'nurses#payable', as: :planning_nurse_payable
  get 'nurses/:id/new_reminder_email' => 'nurses#new_reminder_email', as: :nurse_new_reminder_email
  patch 'nurses/:id/send_reminder_email' => 'nurses#send_reminder_email', as: :nurse_send_reminder_email
  patch 'nurses/:id/master_to_schedule' => 'nurses#master_to_schedule', as: :nurse_master_to_schedule
  get 'nurses/:id/new_master_to_schedule' => "nurses#new_master_to_schedule", as: :new_nurse_master_to_schedule
  get 'master_availabilities/nurses' => 'nurses#master_availabilities', as: :nurses_master_availabilities
  patch 'nurses/:id/archive' => 'nurses#archive', as: :nurse_archive
  patch 'nurses/:id/recalculate_salary' => 'nurses#recalculate_salary', as: :nurse_recalculate_salary
  get 'smart_search/nurses' => 'nurses#smart_search', as: :nurses_smart_search
  get 'smart_search_results/nurses' => 'nurses#smart_search_results', as: :nurses_smart_search_results

  #custom routes for patients
  patch 'patients/:id/toggle_active' => 'patients#toggle_active', as: :toggle_active
  patch 'patients/:id/master_to_schedule' => 'patients#master_to_schedule', as: :patient_master_to_schedule
  get 'patients/:id/new_master_to_schedule' => "patients#new_master_to_schedule", as: :new_patient_master_to_schedule
  get 'plannings/:planning_id/patients/:id/payable' => 'patients#payable', as: :planning_patient_payable
  get 'patients/:id/commented_appointments' => 'patients#commented_appointments', as: :patient_commented_appointments
  get 'patients/:id/teikyohyo' => 'patients#teikyohyo', as: :patient_teikyohyo
  get 'patients/:id/new_extract_care_plan' => 'patients#new_extract_care_plan', as: :patient_new_extract_care_plan
  get 'patients/:id/extract_care_plan' => 'patients#extract_care_plan', as: :patient_extract_care_plan
  get 'search_by_kana_group/patients' => 'patients#search_by_kana_group', as: :patients_search_by_kana_group
  get 'patients/:id/completion_reports_summary' => 'patients#completion_reports_summary', as: :patient_completion_reports_summary

  #custom routes for plannings
  get 'plannings/:id/monthly_general_report' => 'plannings#monthly_general_report', as: :planning_monthly_general_report
  get 'plannings/:id/monthly_appointments_report' => 'plannings#monthly_appointments_report', as: :planning_monthly_appointments_report
  get 'plannings/:id/teams_report' => 'plannings#teams_report', as: :planning_teams_report
  get 'plannings/:id/recent_patients_report' => 'plannings#recent_patients_report', as: :planning_recent_patients_report
  get 'plannings/:id/master' => 'plannings#master', as: :planning_master
  get 'plannings/:id/all_nurses_payable' => 'plannings#all_nurses_payable', as: :planning_all_nurses_payable
  get 'plannings/:id/all_patients_payable' => 'plannings#all_patients_payable', as: :planning_all_patients_payable
  get 'plannings/:id/duplicate_from' => 'plannings#duplicate_from', as: :planning_duplicate_from
  patch 'plannings/:id/duplicate' => 'plannings#duplicate', as: :planning_duplicate
  patch 'plannings/:id/master_to_schedule' => 'plannings#master_to_schedule', as: :master_to_schedule
  get 'plannings/:id/new_master_to_schedule' => 'plannings#new_master_to_schedule', as: :new_planning_master_to_schedule
  get 'plannings/:id/cancelled_report' => 'plannings#cancelled_report', as: :planning_cancelled_report  
  get 'plannings/:id/completion_reports_summary' => 'plannings#completion_reports_summary', as: :planning_completion_reports_summary

  #custom routes for appointments
  patch 'plannings/:planning_id/appointments/:id/toggle_cancelled' => 'appointments#toggle_cancelled', as: :planning_appointment_toggle_cancelled
  patch 'plannings/:planning_id/appointments/:id/toggle_edit_requested' => 'appointments#toggle_edit_requested', as: :planning_appointment_toggle_edit_requested
  patch 'plannings/:planning_id/appointments/:id/archive' => 'appointments#archive', as: :planning_appointment_archive
  get 'new_batch_action/appointments' => 'appointments#new_batch_action', as: :new_appointments_batch_action
  get 'batch_action_confirm/appointments' => 'appointments#batch_action_confirm', as: :appointments_batch_action_confirm
  patch 'batch_archive/appointments' => 'appointments#batch_archive', as: :appointments_batch_archive
  patch 'batch_cancel/appointments' => 'appointments#batch_cancel', as: :appointments_batch_cancel
  patch 'batch_restore_to_operational/appointments' => 'appointments#batch_restore_to_operational', as: :appointments_batch_restore_to_operational
  patch 'batch_request_edit/appointments' => 'appointments#batch_request_edit', as: :appointments_batch_request_edit 
  patch 'appointments/:id/toggle_verified' => 'appointments#toggle_verified', as: :toggle_verified_appointment
  patch 'appointments/:id/toggle_second_verified' => 'appointments#toggle_second_verified', as: :toggle_second_verified_appointment
  get 'appointments/:id/new_cancellation_fee' => 'appointments#new_cancellation_fee', as: :appointment_new_cancellation_fee
  get 'appointments_by_category_report/appointments' => 'appointments#appointments_by_category_report', as: :appointments_by_category_report
  get 'monthly_revenue_report/appointments' => 'appointments#monthly_revenue_report', as: :appointments_monthly_revenue_report

  #custom routes for recurring_appointments
  patch 'planning/:planning_id/recurring_appointments/:id/archive' => 'recurring_appointments#archive', as: :planning_recurring_appointment_archive
  patch 'plannings/:planning_id/recurring_appointments/:id/terminate' => 'recurring_appointments#terminate', as: :planning_recurring_appointment_terminate 
  patch 'plannings/:planning_id/recurring_appointments/:id/create_individual_appointments' => 'recurring_appointments#create_individual_appointments', as: :planning_recurring_appointment_create_individual_appointments

  #custom routes for nurse_service_wages
  patch 'nurses/:nurse_id/services/:service_id/set_nurse_wage' => 'nurse_service_wages#set_nurse_wage', as: :set_nurse_service_wage

  #custom routes for tags
  get '/tags' => 'tags#index'

  #custom routes for dashboard

app/helpers/recurring_appointments_helper.rb
module RecurringAppointmentsHelper

    def url_for_recurring_completion_report(recurring_appointment, date_params)
        date = date_params.to_date rescue Date.today
        if recurring_appointment.completion_report.present?
            edit_recurring_appointment_completion_report_path(recurring_appointment, recurring_appointment.completion_report, date: date_params, start: date, end: (date.end_of_month + 14.days))
        else
            new_recurring_appointment_completion_report_path(recurring_appointment, start: date, end: (date.end_of_month + 14.days))
        end
    end

end

app/views/recurring_appointments/_edit.html.erb
<div id="edit_recurring_appointment" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="colibri-small-title">マスター編集</h1>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<div>
				<%= render 'form', recurring_appointment: @recurring_appointment %>
			</div>

			<% unless @activities.empty? %>
				<div class="modal-body light-blue-background">
					<div class="appointment-section-title">編集履歴</div>
					<% @activities.each do |activity| %>
						<%= render partial: 'activities/activity', locals: {activity: activity} %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>

</div>

app/views/recurring_appointments/_form.html.erb
<%= form_with model: recurring_appointment, url: [@planning, recurring_appointment] do |form| %>
  <% if recurring_appointment.errors.any? %>
  <div id="error_explanation">
    <h2>エラーが発生しました：</h2>

    <ul>
      <% recurring_appointment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <% unless recurring_appointment.new_record? %>
    <div id="form-options-container" class="blue-background-form">
      <div class="modal-subsection-title">簡易編集</div>
        <div class="form-group">
          <span class='colibri-form-label-dark'>繰り返し/期間</span>
          <%= frequency_to_text(recurring_appointment) %><%= weekday_full(recurring_appointment.anchor) %>
          <%= recurring_appointment.anchor.strftime("%-m月%-d日") %> ~ <%= recurring_appointment.termination_date.strftime("%-m月%-d日") if recurring_appointment.termination_date.present? %>
        </div>

        <% if @corporation.elderly_care? %>
          <%= link_to "<i class='glyphicon glyphicon-file' style='color:white;font-size:12px'></i> #{completion_report_text(recurring_appointment)}".html_safe, url_for_recurring_completion_report(recurring_appointment, params[:date]), remote: true, class: 'btn btn-secondary btn-sm btn-margin-bottom' %>
        <% end %>
        <div class='btn btn-secondary btn-sm text-white' id='recurring-appointment-terminate' data-terminate-url="<%= planning_recurring_appointment_terminate_path(@planning, recurring_appointment) %>">サービス停止</div>
        <%= link_to '<i class="glyphicon glyphicon-trash" style="color:white;font-size:12px"></i> 全繰り返し削除'.html_safe, planning_recurring_appointment_archive_path(@planning, recurring_appointment), method: :patch, remote: true, class: 'btn btn-secondary btn-sm btn-margin-bottom', data: {confirm: '全ての繰り返しが削除されます。実績は全てキャンセルされます。'}  %>
    </div>
  <% end %>



  <div class="modal-body">
    <% unless recurring_appointment.new_record? %>
      <div class="modal-subsection-title">詳細編集</div>
    <% end %>
    
    <% if recurring_appointment.new_record? %>

      <div class="form-group">
        <%= form.label :frequency, "頻度", class: "colibri-form-label-dark" %><span class='required-field'>*</span>
        <%= form.select(:frequency,  options_for_select([['毎週',0], ['隔週',7], ['その日のみ', 2], ['毎月第一、三、五週目', 1], ['毎月第二、四週目', 3], ['毎月第一○曜日', 4], ['毎月第二○曜日', 8], ['毎月第三○曜日', 9], ['毎月第四○曜日', 10], ['毎月最後の週', 5], ['毎月最後の週以外毎週', 6], ['3ヶ月ごと同じ週の○曜日', 11]], recurring_appointment.frequency || 0), id: :recurring_appointment_frequency) %>
      </div>

    <% end %>

      <% unless recurring_appointment.new_record? %>
        <div class="form-group">
          <%= form.label :editing_occurrences_after, '編集するサービス', class: "colibri-form-label-dark" %><span class='required-field'>*</span>
          <%= form.select :editing_occurrences_after, options_for_select([params[:date]], params[:date]), {prompt: '全繰り返し'}, {id: :recurring_appointment_editing_occurrences_after} %>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :service_id, "サービスタイプ", class: "colibri-form-label-dark" %><span class='required-field'>*</span>
        <%= form.select :service_id, grouped_options_for_select(@services, recurring_appointment.service_id), {}, {id: :recurring_appointment_service_id, required: true} %>
      </div>

      <div class="form-group">
        <%= form.label :nurse_id, "従業員名", class: "colibri-form-label-dark" %><span class='required-field'>*</span>
        <%= form.select :nurse_id, grouped_options_for_select(@grouped_nurses_for_select, recurring_appointment.nurse_id), {}, {required: true, id: :recurring_appointment_nurse_id} %>
      </div>

      <div class="form-group">
        <%= form.label :patient_id, "#{client_resource_name(@corporation.business_vertical)}名", class: "colibri-form-label-dark" %><span class='required-field'>*</span>
        <%= form.collection_select(:patient_id, @patients, :id, :name, {}, {required: true, disabled: !recurring_appointment.new_record?, id: :recurring_appointment_patient_id}) %>
      </div>

      <div class="form-group colibri-datetime-group">
        <div>
          <%= form.label :anchor, "開始", class: "colibri-form-label-dark", style: 'min-width:60px' %>
        </div>
        <div class="colibri-datetime-input-container">
          <% if @recurring_appointment.new_record? %>
          <div class="colibri-date-input">
            <%= form.date_select :anchor, id: :recurring_appointment_anchor, class: "form-control" %><span class="colibri-datetime-separator">—</span> 
          </div>
          <% end %>
          <div>
            <%= form.time_select :starts_at, minute_step: 5 %>
          </div>
        </div>
      </div>

      <div class="form-group colibri-datetime-group">
        <div>
          <%= form.label :end_day, "終了", class: "colibri-form-label-dark", style: 'min-width:60px' %>
        </div>
        <div class="colibri-datetime-input-container">
          <% if @recurring_appointment.new_record? %>
          <div class="colibri-date-input">
            <%= form.date_select :end_day, id: :recurring_appointment_anchor, class: "form-control" %><span class="colibri-datetime-separator">—</span> 
          </div>
          <% end %>
          <div>
            <%= form.time_select :ends_at, minute_step: 5 %>
          </div>
        </div>
      </div>

      <div class="form-group" style="display:flex">
        <div>
          <%= form.label :color, "カラー", class: "colibri-form-label-dark", style: 'min-width:60px' %>
        </div>
        <div style="width:200px">
          <%= form.select :color,  options_for_select([['デフォルト', '#7AD5DE'], ['青', '#3D9BF3'], ['緑', '#3BC359'], ['ピンク', '#EE59A6'], ['紫', '#A587F6'], ['オレンジ', '#F98050'], ['黄色', '#FBC32D'], ['赤', '#EE584C']], recurring_appointment.color), {}, id: 'color-select' %>
        </div>
      </div> 

      <div class="form-group">
        <%= form.label :description, "繰り返しの指示", class: "colibri-form-label-dark" %>
        <%= form.text_area :description, id: :recurring_appointment_description, class: "form-control" %>
      </div>

      <% unless recurring_appointment.new_record? %>
        <div class="form-group">
          <%= form.label :synchronize_appointments, "実績サービスを含めて編集する  ", class: "colibri-form-label-dark" %>
          <%= form.check_box :synchronize_appointments, checked: true %>
        </div>
      <% end %>

      <%= hidden_field_tag(:start, Date.today) %>
      <%= hidden_field_tag(:end, Date.today) %>    
      <%= hidden_field_tag :patient_resource, true if params[:patient_resource].present? %>


      <div class="actions">
        <%= form.submit '確定（マスター）', class: 'btn btn-info btn-block', id: 'save-recurring-appointment', data: {ripple: ""} %>
      </div>
  </div>
<% end %>

app/views/recurring_appointments/_new.html.erb
<div id="new_recurring_appointment" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="colibri-small-title">新規サービス（マスター）</h1>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<div>
				<%= render 'form', recurring_appointment: @recurring_appointment %>
			</div>
		</div>
	</div>

</div>

app/views/recurring_appointments/_new_individual_appointments.html.erb
<div id="new_individual_appointments" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="colibri-small-title">実績シフトへの反映</h1>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
        <div id="master-save-success" style="margin-bottom:10px" class="colibri-success-notification">サービスがマスターにセーブされました！</div>
        <div id="create-appointments-question" style="margin-bottom:10px">今作成したサービスを実績シフトへ反映する場合は、反映したい年と月を選択してください</div>

        <div id="option1" style="margin-bottom:10px">
          <%= select_tag '年', options_for_select([['2019年', 2019], ['2020年', 2020], ['2021年', 2021]], @recurring_appointment.anchor.year), id: 'reflect-year-1' %>
          <%= select_tag '月', options_for_select([['1月', 1],['2月', 2], ['3月', 3], ['4月', 4], ['5月',5], ['6月',6], ['7月', 7], ['8月', 8], ['9月', 9], ['10月', 10], ['11月', 11], ['12月', 12]], @recurring_appointment.anchor.month), id: 'reflect-month-1' %>
        </div>

        <div id="option2" style="display:none;margin-bottom:10px">
          <%= select_tag '年', options_for_select([['2018年', 2018],['2019年', 2019], ['2020年', 2020], ['2021年', 2021]], (@recurring_appointment.anchor + 1.month).year), id: 'reflect-year-2' %>
          <%= select_tag '月', options_for_select([['1月', 1],['2月', 2], ['3月', 3], ['4月', 4], ['5月',5], ['6月',6], ['7月', 7], ['8月', 8], ['9月', 9], ['10月', 10], ['11月', 11], ['12月', 12]], (@recurring_appointment.anchor + 1.month).month), id: 'reflect-month-2' %>
          <button class="close" style="text-align:left !important;float:none !important" id='remove-second-option-button'>&times;</button>
        </div>

        <div id="option3" style="display:none;margin-bottom:10px">
          <%= select_tag '年', options_for_select([['2018年', 2018],['2019年', 2019], ['2020年', 2020], ['2021年', 2021]], (@recurring_appointment.anchor + 2.months).year), id: 'reflect-year-3' %>
          <%= select_tag '月', options_for_select([['1月', 1],['2月', 2], ['3月', 3], ['4月', 4], ['5月',5], ['6月',6], ['7月', 7], ['8月', 8], ['9月', 9], ['10月', 10], ['11月', 11], ['12月', 12]], (@recurring_appointment.anchor + 2.months).month), id: 'reflect-month-3' %>
          <button class="close" style="text-align:left !important;float:none !important" id='remove-third-option-button'>&times;</button>
        </div>

        <%= label_tag :second_option_selected, class: 'btn btn-colibri-light btn-sm', id: 'second-option-selected-button' do %>
          <%= check_box_tag :second_option_selected, 1, false, {style: "display:none"} %>
          +反映する月を追加
        <% end %>
        
        <%= label_tag :third_option_selected, class: 'btn btn-colibri-light btn-sm', id: 'third-option-selected-button', style: 'display:none' do %>
          <%= check_box_tag :third_option_selected, 1, false, {style: "display:none"} %>
          +反映する月を追加
        <% end %>
      </div>

      <div class="modal-footer">
        <button type='button' class='btn btn-light' data-dismiss='modal'>閉じる</button>
        <div data-url="<%= planning_recurring_appointment_create_individual_appointments_path(@planning, @recurring_appointment) %>" class="btn btn-info" id="create-appointments-trigger">反映する</div>
			</div>
		</div>
	</div>

</div>

app/views/recurring_appointments/_phone_edit.html.erb
<div class="phone_activity_container">
    <div class="activity_header">
        <div class="activity_back_button">
            <%= image_tag "back_arrow_white.svg", width: '25px', class: 'activity_back_icon' %>
        </div>
        <div class="activity_title">
            マスター編集
        </div>
    </div>
    <div class="activity_body">
        <%= render "form", recurring_appointment: @recurring_appointment %>
    </div>
</div>

app/views/recurring_appointments/archive.js.erb
<% if @recurring_appointment.errors.any?  %>
  alert("<%= j @recurring_appointment.errors.values.join('; ') %>");

<% else %>
  $('.modal').modal('hide');
  $('.modal-backdrop').remove();
      $('.activity_back_button').click();

  if (window.fullCalendar) {
    let events = window.fullCalendar.getEvents()
    window.fullCalendar.batchRendering(function(){
      for (let event of events) {
        if (event.id === '<%= j "recurring_#{@recurring_appointment.id}" %>') {
          event.remove()
        }
      }
    })
  }


<% end %>

app/views/recurring_appointments/create.js.erb
<% if @recurring_appointment.errors.any? %>
    alert("<%= j '従業員が重複しています。' %>")
<% else %>
  $('.modal').modal('hide');
  $('.modal-backdrop').remove();
  $('.popover').popover('hide');

  if (typeof renderEvent === 'undefined') {
    let renderEvent
  }
  
  renderEvent = (window.currentResourceType === 'team') || (!window.currentResourceType && window.defaultResourceType === 'team') || (window.currentResourceType === 'nurse' && ['all', '<%= @recurring_appointment.nurse_id %>'].includes(window.currentResourceId)) || (window.currentResourceType === 'patient' && ['all', '<%= @recurring_appointment.patient_id %>'].includes(window.currentResourceId) ) ||  (!window.currentResourceType && (window.defaultResourceType === 'nurse' && ['all', '<%= @recurring_appointment.nurse_id %>'].includes(window.defaultResourceId)) || (window.defaultResourceType === 'patient' && ['all', '<%= @recurring_appointment.patient_id %>'].includes(window.defaultResourceId)) )

  if (window.fullCalendar && renderEvent) {
    window.fullCalendar.batchRendering(function(){
      events = $.parseJSON("<%= j render(partial: 'recurring_appointments/recurring_appointment.json', locals: {recurring_appointment: @recurring_appointment}).html_safe %>")
      for (let event of events) {
        window.fullCalendar.addEvent(event, 'url1')
      }
    })
  }

  $('#remote_container').html('<%= j render "new_individual_appointments" %>');
  $('#new_individual_appointments').modal('show');
  selectSecondAppointmentCopyOption()
  submitAppointmentCopyOption()
<% end %>

app/views/recurring_appointments/create_individual_appointments.js.erb
$('.modal').modal('hide');

app/views/recurring_appointments/edit.js+phone.erb
$('#remote_container').html('<%= j render "phone_edit" %>');
$('#detail-container').hide()
$('.popover').popover('hide');

mobileScrollTop()

recurringAppointmenSelectizeTitle();
recurringAppointmentSelectizeNursePatient();
toggleEditRequested();
toggleCancelled();
editAfterDate();
colorSelectize()

$('.activity_back_button').click(function(){
    $('.phone_activity_container').hide()
    $('#detail-container').show()
})

app/views/recurring_appointments/edit.js.erb
$('.modal').modal('hide');
$('#remote_container').html('<%= j render "edit" %>');
$('.popover').popover('hide');
$('#edit_recurring_appointment').modal('show');
recurringAppointmenSelectizeTitle();
recurringAppointmentSelectizeNursePatient();
toggleEditRequested();
toggleCancelled();
editAfterDate();
colorSelectize()

app/views/recurring_appointments/index.js.erb
$('#recurring-appointment-details').empty();
<% @occurrence_appointments.each do |occurrence, recurring_appointment| %>
	$('#recurring-appointment-details').append('<%= j render partial: "recurring_appointments/recurring_appointment", locals: {occurrence: occurrence, recurring_appointment: recurring_appointment}  %>');
<% end %>

app/views/recurring_appointments/new.js.erb
$('.modal').modal('hide');
$('.modal-backdrop').remove();
$('#remote_container').html('<%= j render "new" %>');
$('#new_recurring_appointment').modal('show');
toggleEditRequested();
recurringAppointmenSelectizeTitle();
colorSelectize()

app/views/recurring_appointments/terminate.js.erb
<% if @recurring_appointment.errors.any?  %>
  alert("<%= j @recurring_appointment.errors.values.join('; ') %>");
<% else %>
  $('.modal').modal('hide');
  $('.activity_back_button').click();

  if (window.fullCalendar) {
    window.fullCalendar.batchRendering(function(){
      let events = window.fullCalendar.getEvents()
      for (let event of events) {
        if (event.id === '<%= j "recurring_#{@recurring_appointment.id}" %>') {
          event.remove()
        }
      }

      let newEvents = $.parseJSON("<%= j render(partial: 'recurring_appointments/recurring_appointment.json', locals: {recurring_appointment: @recurring_appointment}).html_safe %>")

      for (let newEvent of newEvents) {
        window.fullCalendar.addEvent(newEvent, 'url1')
      }
    })
  }

<% end %>