config/routes.rb
Rails.application.routes.draw do

  post 'user_token' => 'user_token#create'
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: ['www', 'scheduler']}
  get 'bonuses/new'

  get 'calendar_event/new'

  get 'contact_form/new'

  get 'contact_form/create'

  get 'tags/index'

  namespace :api, defaults: {format: :json} do 
    namespace :v1 do
      resources :appointments
      resources :corporations
    end
  end

  devise_for :users, controllers: {
    invitations: "invitations",
    sessions: "sessions",
    registrations: "registrations"
  }

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :users, only: [:index, :edit, :update]


  resources :plannings do
  	resources :appointments, except: [:destroy, :new]
  	resources :recurring_appointments, except: :destroy
    resources :private_events, except: :new
    resources :wished_slots
    resources :nurses
    resources :patients
    resources :activities
    resources :printing_options, only: :show
    resources :teams, only: :show
  end

  resources :services

  resources :care_manager_corporations do
    resources :care_managers
  end

  resources :calendar_events, only: :new

  resources :salary_line_items, only: [:update, :destroy]

  resources :patients do 
    resources :care_plans
  end

  resources :posts

  resources :appointments, except: [:destroy, :new] do
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :recurring_appointments do 
    resources :completion_reports, except: [:index, :destroy]
  end

  resources :completion_reports, only:[:index, :destroy]

  resources :nurses do
    resources :salary_line_items, except: [:new]
    resources :bonuses, only: :new
    resources :nurse_service_wages, only: :index
    resources :completion_reports, only: :index
  end

  resources :corporations do
    resources :nurses, only: :index
    resources :patients, only: :index
    resources :printing_options, only: :update
  end

  resources :dashboard, only: :index

  resources :teams

  resources :contact_forms, only: [:new, :create]

  resources :salary_rules


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #custom routes for static pages
  get "/pages/*page" => "pages#show", as: :pages

  #custom routes for teams
  get 'plannings/:planning_id/teams/:id/payable' => 'teams#payable', as: :planning_team_payable
  get 'plannings/:planning_id/teams/:id/master' => 'teams#master', as: :planning_team_master
  get 'teams/:id/revenue_per_nurse_report' => 'teams#revenue_per_nurse_report', as: :team_revenue_per_nurse_report
  get 'teams/:id/new_master_to_schedule' => 'teams#new_master_to_schedule', as: :new_team_master_to_schedule
  patch 'teams/:id/master_to_schedule' => 'teams#master_to_schedule', as: :team_master_to_schedule
  get 'teams/:id/completion_reports_summary' => 'teams#completion_reports_summary', as: :team_completion_reports_summary


  #custom routes for corporations
  get 'corporations/:id/revenue_per_team_report' => 'corporations#revenue_per_team_report', as: :corporation_revenue_per_team_report
  get 'corporations/:id/new_email_monthly_nurse_wages' => 'corporations#new_email_monthly_nurse_wages', as: :corporation_new_email_monthly_nurse_wages
  get 'corporations/:id/email_monthly_nurse_wages' => 'corporations#email_monthly_nurse_wages', as: :corporation_email_monthly_nurse_wages

  #custom routes for users
  patch 'users/:id/toggle_admin' => 'users#toggle_admin', as: :toggle_admin
  get 'users/:id/edit_role' => 'users#edit_role', as: :edit_user_role
  patch 'users/:id/update_role' => 'users#update_role', as: :update_user_role
  get 'users/current_user_home' => 'users#current_user_home', as: :current_user_home
  
  #custom routes for nurses
  get 'plannings/:planning_id/nurses/:id/payable' => 'nurses#payable', as: :planning_nurse_payable
  get 'nurses/:id/new_reminder_email' => 'nurses#new_reminder_email', as: :nurse_new_reminder_email
  patch 'nurses/:id/send_reminder_email' => 'nurses#send_reminder_email', as: :nurse_send_reminder_email
  patch 'nurses/:id/master_to_schedule' => 'nurses#master_to_schedule', as: :nurse_master_to_schedule
  get 'nurses/:id/new_master_to_schedule' => "nurses#new_master_to_schedule", as: :new_nurse_master_to_schedule
  get 'master_availabilities/nurses' => 'nurses#master_availabilities', as: :nurses_master_availabilities
  patch 'nurses/:id/archive' => 'nurses#archive', as: :nurse_archive
  patch 'nurses/:id/recalculate_salary' => 'nurses#recalculate_salary', as: :nurse_recalculate_salary
  get 'smart_search/nurses' => 'nurses#smart_search', as: :nurses_smart_search
  get 'smart_search_results/nurses' => 'nurses#smart_search_results', as: :nurses_smart_search_results

  #custom routes for patients
  patch 'patients/:id/toggle_active' => 'patients#toggle_active', as: :toggle_active
  patch 'patients/:id/master_to_schedule' => 'patients#master_to_schedule', as: :patient_master_to_schedule
  get 'patients/:id/new_master_to_schedule' => "patients#new_master_to_schedule", as: :new_patient_master_to_schedule
  get 'plannings/:planning_id/patients/:id/payable' => 'patients#payable', as: :planning_patient_payable
  get 'patients/:id/commented_appointments' => 'patients#commented_appointments', as: :patient_commented_appointments
  get 'patients/:id/teikyohyo' => 'patients#teikyohyo', as: :patient_teikyohyo
  get 'patients/:id/new_extract_care_plan' => 'patients#new_extract_care_plan', as: :patient_new_extract_care_plan
  get 'patients/:id/extract_care_plan' => 'patients#extract_care_plan', as: :patient_extract_care_plan
  get 'search_by_kana_group/patients' => 'patients#search_by_kana_group', as: :patients_search_by_kana_group
  get 'patients/:id/completion_reports_summary' => 'patients#completion_reports_summary', as: :patient_completion_reports_summary

  #custom routes for plannings
  get 'plannings/:id/monthly_general_report' => 'plannings#monthly_general_report', as: :planning_monthly_general_report
  get 'plannings/:id/monthly_appointments_report' => 'plannings#monthly_appointments_report', as: :planning_monthly_appointments_report
  get 'plannings/:id/teams_report' => 'plannings#teams_report', as: :planning_teams_report
  get 'plannings/:id/recent_patients_report' => 'plannings#recent_patients_report', as: :planning_recent_patients_report
  get 'plannings/:id/master' => 'plannings#master', as: :planning_master
  get 'plannings/:id/all_nurses_payable' => 'plannings#all_nurses_payable', as: :planning_all_nurses_payable
  get 'plannings/:id/all_patients_payable' => 'plannings#all_patients_payable', as: :planning_all_patients_payable
  get 'plannings/:id/duplicate_from' => 'plannings#duplicate_from', as: :planning_duplicate_from
  patch 'plannings/:id/duplicate' => 'plannings#duplicate', as: :planning_duplicate
  patch 'plannings/:id/master_to_schedule' => 'plannings#master_to_schedule', as: :master_to_schedule
  get 'plannings/:id/new_master_to_schedule' => 'plannings#new_master_to_schedule', as: :new_planning_master_to_schedule
  get 'plannings/:id/cancelled_report' => 'plannings#cancelled_report', as: :planning_cancelled_report  
  get 'plannings/:id/completion_reports_summary' => 'plannings#completion_reports_summary', as: :planning_completion_reports_summary

  #custom routes for appointments
  patch 'plannings/:planning_id/appointments/:id/toggle_cancelled' => 'appointments#toggle_cancelled', as: :planning_appointment_toggle_cancelled
  patch 'plannings/:planning_id/appointments/:id/toggle_edit_requested' => 'appointments#toggle_edit_requested', as: :planning_appointment_toggle_edit_requested
  patch 'plannings/:planning_id/appointments/:id/archive' => 'appointments#archive', as: :planning_appointment_archive
  get 'new_batch_action/appointments' => 'appointments#new_batch_action', as: :new_appointments_batch_action
  get 'batch_action_confirm/appointments' => 'appointments#batch_action_confirm', as: :appointments_batch_action_confirm
  patch 'batch_archive/appointments' => 'appointments#batch_archive', as: :appointments_batch_archive
  patch 'batch_cancel/appointments' => 'appointments#batch_cancel', as: :appointments_batch_cancel
  patch 'batch_restore_to_operational/appointments' => 'appointments#batch_restore_to_operational', as: :appointments_batch_restore_to_operational
  patch 'batch_request_edit/appointments' => 'appointments#batch_request_edit', as: :appointments_batch_request_edit 
  patch 'appointments/:id/toggle_verified' => 'appointments#toggle_verified', as: :toggle_verified_appointment
  patch 'appointments/:id/toggle_second_verified' => 'appointments#toggle_second_verified', as: :toggle_second_verified_appointment
  get 'appointments/:id/new_cancellation_fee' => 'appointments#new_cancellation_fee', as: :appointment_new_cancellation_fee
  get 'appointments_by_category_report/appointments' => 'appointments#appointments_by_category_report', as: :appointments_by_category_report
  get 'monthly_revenue_report/appointments' => 'appointments#monthly_revenue_report', as: :appointments_monthly_revenue_report

  #custom routes for recurring_appointments
  patch 'planning/:planning_id/recurring_appointments/:id/archive' => 'recurring_appointments#archive', as: :planning_recurring_appointment_archive
  patch 'plannings/:planning_id/recurring_appointments/:id/terminate' => 'recurring_appointments#terminate', as: :planning_recurring_appointment_terminate 
  patch 'plannings/:planning_id/recurring_appointments/:id/create_individual_appointments' => 'recurring_appointments#create_individual_appointments', as: :planning_recurring_appointment_create_individual_appointments

  #custom routes for nurse_service_wages
  patch 'nurses/:nurse_id/services/:service_id/set_nurse_wage' => 'nurse_service_wages#set_nurse_wage', as: :set_nurse_service_wage

  #custom routes for tags
  get '/tags' => 'tags#index'

  #custom routes for dashboard

app/models/planning.rb
class Planning < ApplicationRecord
	include PublicActivity::Common
	
	belongs_to :corporation
	has_many :appointments
	has_many :recurring_appointments
	has_many :private_events
	has_many :wished_slots
	has_many :salary_line_items
	has_many :completion_reports

	before_save :default_title

	private

	def default_title
		self.title = "#{self.business_month}月のスケジュール" if self.title.blank?
	end

end

app/helpers/plannings_helper.rb
module PlanningsHelper

	HIRAGANAS = ['あ','か','さ','た','な','は','ま','や','ら','わ','カナなし'] 

	def insurance_category(boolean)
		boolean ? '医療' : '介護'
	end

	def japanese_date_if_present(date)
		date.present? ? date.strftime('%Y年%-m月%-d日') : '未記入'
	end

	def calendar_resources_url(user, corporation, include_undefined)
		case user.calendar_option
		when 0
			corporation_nurses_path(corporation, include_undefined: include_undefined, format: :json)
		when 1
			corporation_patients_path(corporation, format: :json)
		when 2
			''
		when 3
			corporation_nurses_path(corporation, format: :json, include_undefined: include_undefined, team_id: current_user.default_resource_id)
		else
			corporation_nurses_path(corporation, include_undefined: include_undefined, format: :json)
		end
	end

	def link_to_all_patients_from_view(view, planning, options={})
		case view 
		when 'master'
			planning_all_patients_master_path(planning)
		when 'resource'
			planning_all_patients_path(planning)
		when 'payable'
			planning_all_patients_payable_path(planning, params: {m: options[:month], y: options[:year]})
		else
			''
		end
	end

	def link_to_all_nurses_from_view(view, planning, options={})
		case view 
		when 'master'
			planning_all_nurses_master_path(planning)
		when 'resource'
			planning_all_nurses_path(planning)
		when 'payable'
			planning_all_nurses_payable_path(planning, params: {m: options[:month], y: options[:year]})
		else
			''
		end
	end

	def link_to_planning_nurse_from_view(view, planning, nurse, options={})
		case view 
		when 'master'
			planning_nurse_master_path(planning, nurse)
		when 'resource'
			planning_nurse_path(planning, nurse)
		when 'payable'
			planning_nurse_payable_path(planning, nurse, params: {m: options[:month], y: options[:year]})
		else
			''
		end
	end

	def link_to_planning_patient_from_view(view, planning, patient, options={})
		case view 
		when 'master'
			planning_patient_master_path(planning, patient)
		when 'resource'
			planning_patient_path(planning, patient)
		when 'payable'
			planning_patient_payable_path(planning, patient, params: {m: options[:month], y: options[:year]})
		else
			''
		end
	end

	def laptop_report_icon(view)
		if view == 'admin_reports'
			'white-report.svg'
		else
			'light-grey-report.svg'
		end
	end

	def report_icon(view)
		if view == 'admin_reports'
			'dark-grey-report.svg'
		else
			'grey-report.svg'
		end
	end

	


end

app/views/plannings/_drag_drop_modal.html.erb
<div id="drag-drop-modal" class="modal fade" style="display:none">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="colibri-small-title">サービス編集確認</h1>
				<button type="button" data-dismiss="modal" class="close close-drag-drop-modal">&times;</button>
			</div>
			<div class="modal-body">
				<p>下記の情報が編集されます。</p>
				<div id="drag-drop-content"></div>
			</div>
			<div class="modal-footer">
				<div class="btn btn-colibri-light btn-pointer close-drag-drop-modal">キャンセル</div>
				<div class="btn btn-info text-white btn-pointer" id="drag-drop-save">確定</div>
			</div>
		</div>
	</div>
</div>

app/views/plannings/_phone_bottom_menu.html.erb
<div id="planning-menu-container" class="no-print">
	<div id="planning-menu-list" style="padding-left:5px;padding-right:5px;">
		<ul id="left-menu-ul" class="nav-tabs <%= 'nurse-restricted-nav' if current_user.nurse_restricted? %>">
			<% unless current_user.nurse_restricted? %>
				<li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'home' %>" data-url="<%= dashboard_index_path %>" title="ホーム.ダッシュボード"><span class="glyphicon glyphicon-home <%= view == 'home' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="font-size:24px"></span></li>
			<% end %>
			<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'resource' %>" data-url="<%= planning_path(@planning) %>" title="実績シフト"><span class="glyphicon glyphicon-calendar <%= view == 'resource' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="margin-left:3px;font-size:24px"></span></li>
			<% unless current_user.has_restricted_access? %>
				<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'admin_reports' %>" data-url="<%= current_user.nurse.try(:team).present? ? team_completion_reports_summary_path(current_user.nurse.try(:team)) : planning_completion_reports_summary_path(@planning) %>" style="margin-left:17px;margin-right:17px" title="実施記録"><%= image_tag(report_icon(view), width: '30px') %></li>
			<% end %>
			<% if current_user.nurse_restricted? %>
				<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'reports' %>" data-url="<%= completion_reports_path(params: {m: Date.today.in_time_zone('Tokyo').month, y: Date.today.in_time_zone('Tokyo').year}) %>" title="実施記録"><span class="glyphicon glyphicon-file <%= view == 'reports' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="margin-left:3px;font-size:24px"></span></li>
			<% end %>
            <% unless current_user.nurse_restricted? %>
                <li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'master' %>" data-url="<%=  planning_master_path(@planning) %>" title="マスター">マ</li>
                <li class="planning-menu-items" id="more-planning-menu-button"><%= image_tag('grey-dots.svg', width: '20px') %></li>
            <% end %>
        </ul>
	</div>
</div>
<div id="more-planning-menu-items" style='display:none'>
    <ul id="more-menu-items-list">
        <% unless current_user.has_restricted_access? %>
            <li class="planning-menu-items more-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'payable' %>" data-url="<%= resource_payable_path %>" id="go-to-payable" title="給与.請求">給</li>
        <% end %>
        <li class="planning-menu-items more-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'settings' %>"  data-url="<%= patients_path %>" title="設定"><span class="glyphicon glyphicon-cog <%= view == 'settings' ? 'glyphicon-selected' : 'glyphicon-default' %>" style="font-size:25px"></span></li>
    </ul>
</div>

app/views/plannings/_planning_left_menu.html.erb
<div id="planning-menu-container" class="no-print">
	<div id="planning-menu-list">
		<ul id="left-menu-ul" class="nav-tabs <%= 'nurse-restricted-nav' if current_user.nurse_restricted? %>">
			<% unless (current_user.nurse_restricted? || current_user.schedule_readonly?) %>
				<li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'home' %>" data-url="<%= dashboard_index_path %>" title="ホーム.ダッシュボード"><span class="glyphicon glyphicon-home <%= view == 'home' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="font-size:24px"></span></li>
			<% end %>
			<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'resource' %>" data-url="<%= planning_path(@planning) %>" title="実績シフト"><span class="glyphicon glyphicon-calendar <%= view == 'resource' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="margin-left:3px;font-size:24px"></span></li>
			<% unless current_user.has_restricted_access? %>
				<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'admin_reports' %>" data-url="<%= current_user.nurse.try(:team).present? ? team_completion_reports_summary_path(current_user.nurse.try(:team)) : planning_completion_reports_summary_path(@planning) %>" title="実施記録"><%= image_tag(laptop_report_icon(view)) %></li>
			<% end %>
			<% unless current_user.has_restricted_access? %>
				<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'payable' %>" data-url="<%= resource_payable_path %>" id="go-to-payable" title="給与.請求">給</li>
			<% end %>
			<% if current_user.nurse_restricted? %>
				<li class="planning-menu-items colibri-clickable-link  <%= 'planning-menu-selected' if view == 'reports' %>" data-url="<%= completion_reports_path(params: {m: Date.today.in_time_zone('Tokyo').month, y: Date.today.in_time_zone('Tokyo').year}) %>" title="実施記録"><span class="glyphicon glyphicon-file <%= view == 'reports' ? 'glyphicon-selected' : 'glyphicon-default' %>"  style="margin-left:3px;font-size:24px"></span></li>
			<% end %>
			<% unless current_user.nurse_restricted? %>
				<li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'master' %>" data-url="<%=  planning_master_path(@planning) %>" title="マスター">マ</li>
			<% end %>
			<% unless current_user.role == "nurse_restricted" %>
				<% if current_user.schedule_readonly? %>
					<li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'settings' %>"  data-url="<%= edit_user_path(current_user) %>" title="設定"><span class="glyphicon glyphicon-cog <%= view == 'settings' ? 'glyphicon-selected' : 'glyphicon-default' %>" style="font-size:25px"></span></li>
				<% else %>
					<li class="planning-menu-items colibri-clickable-link <%= 'planning-menu-selected' if view == 'settings' %>"  data-url="<%= patients_path %>" title="設定"><span class="glyphicon glyphicon-cog <%= view == 'settings' ? 'glyphicon-selected' : 'glyphicon-default' %>" style="font-size:25px"></span></li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

app/views/plannings/_settings_submenu.html.erb
<div id="settings-menu-container" class="no-print scrollbar-custom colibri-scrollbar-dark">
	<div id="settings-menu-list">
        <ul id="settings-list">
          <li class="setting-list-element close" id="close-settings">&times;</li>
          <% if !current_user.has_restricted_access? %>
          <li class="settings-list-header">データ</li>
            <li id="patients" class="settings-list-element <%= "settings-list-element-selected" if view == "patients" %>"><%= link_to "#{client_resource_name(@corporation.business_vertical)}一覧", patients_path, class: 'settings-list-url' %></li>
            <li id="nurses" class="settings-list-element <%= "settings-list-element-selected" if view == "nurses" %>"><%= link_to '従業員一覧', nurses_path, class: 'settings-list-url' %></li>
            <% if @corporation.elderly_care_and_nursing? %>
              <li id="care-managers" class="settings-list-element <%= "settings-list-element-selected" if view == "care_manager_corporations" %>"><%= link_to '居宅一覧', care_manager_corporations_path, class: 'settings-list-url' %></li>
            <% end %> 
          <% end %>
          <% if current_user.has_admin_access? %>
            <li class="settings-list-header" style="margin-top:15px"><%= corporation_resource_name(@corporation.business_vertical) %>設定</li>
              <li id="teams" class="settings-list-element <%= "settings-list-element-selected" if view == "teams" %>"><%= link_to 'チーム管理', teams_path, class: 'settings-list-url' %></li>
              <li id="users" class="settings-list-element <%= "settings-list-element-selected" if view == "users" %>"><%= link_to 'ユーザー招待.権限', users_path, class: 'settings-list-url' %></li>
              <li id="services" class="settings-list-element <%= "settings-list-element-selected" if view == "services" %>"><%= link_to 'サービスタイプ一覧', services_path, class: 'settings-list-url' %></li>
              <li id="salary_rules" class="settings-list-element <%= "settings-list-element-selected" if view == "salary_rules" %>"><%= link_to '手当一覧', salary_rules_path, class: 'settings-list-url' %></li>
          <% end %>
          <li class="settings-list-header" style="margin-top:15px">設定.履歴</li>
            <li id="user_options" class="settings-list-element <%= "settings-list-element-selected" if view == "user_options" %>"><%= link_to '個人設定', edit_user_path(current_user), class: 'settings-list-url' %></li>
            <li id="user_password" class="settings-list-element <%= "settings-list-element-selected" if view == "user_password" %>"><%= link_to 'パスワード変更', edit_user_registration_path(current_user), class: 'settings-list-url' %></li>
            <% if current_user.has_admin_access? %>
              <li id="settings" class="settings-list-element <%= "settings-list-element-selected" if view == "schedule_settings" %>"><%= link_to '法人設定', edit_corporation_path(@corporation), class: 'settings-list-url' %></li>
              <li id="printing-options" class="settings-list-element <%= "settings-list-element-selected" if view == "printing_options" %>"><%= link_to '印刷オプション', planning_printing_option_path(@planning, @corporation.printing_option), class: 'settings-list-url' %></li>
              <li id="activities" class="settings-list-element <%= "settings-list-element-selected" if view == "activities" %>"><%= link_to '編集履歴', planning_activities_path(@planning), class: 'settings-list-url' %></li>
            <% end %>
            <li id="logout" class="settings-list-element"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'settings-list-url' %></li>
        </ul>
	</div>
</div>

app/views/plannings/all_patients_payable.html.erb
<%= javascript_tag do %>
	window.currentResourceType = 'patient'
	window.currentResourceId = 'all'
<% end %>

<% if request.variant.phone? %>
	<%= render partial: 'plannings/phone_bottom_menu', locals: {view: 'payable', resource_payable_path: planning_all_patients_payable_path(@planning, params: {m: @selected_month, y: @selected_year})} %>
<% else %>
	<%= render partial: 'plannings/planning_left_menu', locals: {view: 'payable', resource_payable_path: planning_all_patients_payable_path(@planning, params: {m: @selected_month, y: @selected_year})} %>
<% end %>

<%= render partial: 'plannings/resources_submenu', locals: {individual_resource: 'false', resource_type: 'patient', view: 'payable'} %>

<% if @corporation.elderly_care_and_nursing? %>


<div id="menu-backdrop">
</div>
<div id="payable-container">
	<div id="payable-title-wrapper">
		<div id="payable-menu">
			<%= image_tag 'hamburger_icon_white.svg', size: '35', class: 'hamburger_menu'  %>
		</div>
		<div class='colibri-xs-title colibri-payable-title no-print' style='margin-left:5px'>請求.実績</div>
	</div>

	<div class="payable-body">
		<div class='no-print' style='margin-left:5px;margin-top:5px'>
			<%= select_tag '年', options_for_select([['2018年', 2018],['2019年', 2019], ['2020年', 2020], ['2021年', 2021]], params[:y]), id: 'query_year' %>
			<%= select_tag '月', options_for_select([['1月', 1],['2月', 2], ['3月', 3], ['4月', 4], ['5月',5], ['6月',6], ['7月', 7], ['8月', 8], ['9月', 9], ['10月', 10], ['11月', 11], ['12月', 12]], params[:m]), id: 'query_month' %>
			<button id='payable-query-trigger' class='btn-colibri-light-gray btn btn-sm'><span class="glyphicon glyphicon-refresh" style="color:white;font-size:0.85em"></span></button>
		</div>

		<div class='colibri-dashboard-container-row no-print'>
			<div class='colibri-dashboard-subcontainer'>
				<div class='colibri-subcontainer-header'>
					<span class='colibri-subcontainer-title'>提供票</span>
				</div>
				<div class='colibri-subcontainer-body'>
				<div style="margin-top:4px;margin-right:4px">
					<%= select_tag :care_manager_corporation_filter, options_for_select(@care_manager_corporations.pluck(:name, :id)), {id: :cm_teikyohyo_filter, multiple: true} %>
				</div>
				<table class="table">
					<% @care_manager_corporations.each do |care_manager_corporation| %>
						<tr id="cm_teikyohyo_<%= care_manager_corporation.id %>" class="cm_teikyohyo">
							<td><%= care_manager_corporation.name %></td>
							<td><%= link_to 'Pdf', care_manager_corporation_teikyohyo_path(care_manager_corporation, params: {m: @selected_month, y: @selected_year}, format: :pdf), target: :_blank, class: 'btn btn-sm btn-success text-white' if current_user.has_admin_access? %></td>
						</tr>
					<% end %>
				</table>
				</div>
			</div>
			<div class='colibri-dashboard-subcontainer'>
				<div class='colibri-subcontainer-header'>
					<span class='colibri-subcontainer-title'>コメント付きサービス</span>
				</div>
				<div class='colibri-subcontainer-body'>
				<div style="margin-top:4px;margin-right:4px">
					<%= select_tag :care_manager_corporation_filter, options_for_select(@care_manager_corporations.pluck(:name, :id)), {id: :cm_filter, multiple: true} %>
				</div>
				<table class="table">
					<% @care_manager_corporations.each do |care_manager_corporation| %>
						<tr id="cm_corporation_<%= care_manager_corporation.id %>" class="cm_corporation">
							<td><%= care_manager_corporation.name %></td>
							<td><%= link_to 'Pdf', care_manager_corporation_commented_appointments_path(care_manager_corporation, params: {m: @selected_month, y: @selected_year}, format: :pdf), target: :_blank, class: 'btn btn-sm btn-success text-white' if current_user.has_admin_access? %></td>
						</tr>
					<% end %>
				</table>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/plannings/new_master_to_schedule.js.erb
$('.modal').modal('hide');
$('.modal-backdrop').remove();
$('#remote_container').html('<%= j render "new_master_to_schedule" %>');
$('#reflect-all-master').modal('show');
submitReflect()